### ISSUE TITLE
Create tutorials for float variants

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1054]
It would be nice to have a take off and a landing tutorials for the float variants.

**Comment by gilbertohasnofb** [comment]
Note: we are in the process of deciding a fixed scenery tile for the tutorials, so please do not work on this before that has been decided. This tile will likely be in Hawaii and so these two tutorials can take place somewhere in the sea close to the selected airport.

**Comment by wkitty42** [comment]
excellent idea... i remember playing around with the amphibious craft and getting it up onto the land... i was playing in the KRDU area and flying over to Jordan Lake to land there and ""camp"" on the shore :)

FWIW: Jordan Lake is west of KRDU... it is the result of flood protection plan started back in 1947, IIRC... we used to go swimming there all the time but life moves on :smile_cat:

**Comment by wlbragg** [comment]
@gilbertohasnofb FYI: the mooring code I'm implementing gives you the option to automatically start at a mooring location if in the float or amphibian configuration. With that comes a list of historical (and some custom) mooring locations that you will start up in if close to that location. We can add a mooring location near whatever the final runway selection is for some consistency. It may fit nicely with whatever hydro tutorials we come up with.

BUMP:
>Note: we are in the process of deciding a fixed scenery tile for the tutorials, so please do not work on this before that has been decided. This tile will likely be in Hawaii and so these two tutorials can take place somewhere in the sea close to the selected airport.

**Comment by wlbragg** [comment]
Comments for whoever does this...

I added an entry for Hilo International, Hawaii PHTO in the mooring code so you can do "Automatic" mooring or "Go now" mooring.
The mooring position is
~~~
<latitude-deg type="double">19.725</latitude-deg>
<longitude-deg type="double">-155.071</longitude-deg>
<heading-deg type="double">190.0</heading-deg>
~~~
I'm not sure exactly what we want for this?
Options are...
1) regular tutorial starting you moored in the mooring spot.
2) tutorial that has you select "Go now"
3) tutorial that has you select "Automatic" mooring

I suppose 1) makes the most sense especially if we can incorporate a how too of the mooring menu choices?

Also there is a 2nd tutorial needed, the landing and setting the mooring.

For that I would either start at PHTO and teach the landing gear procedures at the same time. Then circle to line up on approach to Reed's Bay. The only time I tried it the wind was out of 190 deg. Go through steps of retracting gear in-route (amphibious). Land in the bay and deploy the mooring anchor/buoy. That may get tricky because the wind is a factor in deploying the mooring buoy. I don't know if the tutorial can catch the wind speed and not allow the mooring part if wind speed is to high.
To moor, forward speed has to be at or below 7mph (I think) and you have to be within about 45-50 left or right of wind direction.

**Comment by wlbragg** [comment]
First tutorial is finished, see issue-1054 branch and  Create tutorials for float variants #1163 .

Please test.

**Comment by wlbragg** [comment]
@gilbertohasnofb I made some tweaks, please be sure to pull fresh. Also I may have the landing tutorial done by your tonight. :smile:

**Comment by gilbertohasnofb** [comment]
Cool, I will do another pull before testing later tonight.

> Also I may have the landing tutorial done by your tonight.

If you have that and all will be working as it should, will that mean that the PR will be ready to merge or will we need to still do some work on anything else?

**Comment by wlbragg** [comment]
Yes

**Comment by wlbragg** [comment]
Not quite done, still some tweaking left to do on "Landing Tutorial" and radio settings on both.

**Comment by gilbertohasnofb** [comment]
@wlbragg what's the status of this work? I will wait a bit before reviewing it since you said this is not quite done yet, ok?
