### ISSUE TITLE
Yoke is missing PPT cord

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1098]
There is a noticeable is the telephone cable type thing under the yoke:

![](https://user-images.githubusercontent.com/5700795/39924957-c59dd372-5521-11e8-8a42-9c622a185d2d.jpg)

![image](https://user-images.githubusercontent.com/10434911/39924117-83ef48dc-551e-11e8-8064-9050edea8945.png)

Probably connects to the PTT button?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Ok, a couple of stuff. First, would you mind me editing your post above? 'Fun details' doesn't help much. Then there are a lot of reference photos to a much more modern model of the 172. 

From all you wrote, here is with what I agree:

1) I agree that the original model P has a lighter hole which we can see in my favourite reference, the OH-CTL:

![image](https://user-images.githubusercontent.com/5700795/39924950-b35221d2-5521-11e8-835c-2944ab58d340.png)

2) The yoke cable is only present on the pilot side on the model P as far as I can tell:

![aag](https://user-images.githubusercontent.com/5700795/39924957-c59dd372-5521-11e8-8a42-9c622a185d2d.jpg)

The issue is that will be extremely difficult to model since the cable extends and contracts with movement. I am not sure we are capable of doing that at the moment, and the pain/gain ratio do not look too promising IMO.

3) I will work on the 'pocket' in the bottom right hand side of the panel via textures. I will add that to all panels on the next round of works.

**Comment by legoboyvdlp** [comment]
Thank you for your comment (and the reference images).

As for the cable, I agree that it would be very difficult so definitely we don't need it.

**Comment by gilbertohasnofb** [comment]
About the cable: it is indeed for the Press-To-Talk button. Some examples of the model P do have them on both yokes, though most seem to have only on the pilot side. 

@wlbragg if you ever feel like doing this, here is a possible solution for the cable:

![](http://imgproc.airliners.net/photos/airliners/8/1/6/1287618.jpg?v=v40)

But even this would be difficult to do properly, as the yoke metal bit 'enters' the cockpit. 

Notice that we would also need to include the PPT button:

![](http://aircraftpartsandsalvage.com/images/0513260-5_112.JPG)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I am not too happy with too many unrelated things in a single issue. For instance, if I fix the pocket on the right bottom via texture work, this issue cannot be closed. So If you don't mind, I will edit it and make it only for the yoke cable and I will open new ones for the lighter and for the pocket. Is that all right with you?

**Comment by onox** [comment]
@wlbragg Can we make the PPT cord movement dynamic by re-using the code written for that orange cargo helicopter? Just with fewer parts.

**Comment by wlbragg** [comment]
>Can we make the PPT cord movement dynamic by re-using the code written for that orange cargo helicopter?

You probably could, but I don't think it worth the pain or the overhead. Those ropes are segmented. I think the aircrane's is 30+ segments. Then the math behind it to do what you want.

Yesterday I tried making a 5 segment cord (similar to the mike cord) and used the mike cord texture to test the look. I had it sag slightly in the middle and narrowed the plug end that would plug into the panel. I assume it plugs into the panel?
I think with a decent x and y rotation centered at the panel plug location you could match the yoke rotation close enough. The problem was the forward and back motion of the yoke. Either we use ??? to stretch the cord (same way we do the tie-downs or the original rescue helo rope, or I remove the tapered end and translate the rope end closest the panel into the panel which you can't see anyway. 
Any comments or suggestions?

**Comment by wlbragg** [comment]
FYI: you really cant see the cord in front of the pilot from the plots perspective.

![yoke1](https://user-images.githubusercontent.com/11069680/43153556-35190c54-8f37-11e8-8ab4-fda0a935330a.jpg)

![yoke2](https://user-images.githubusercontent.com/11069680/43153558-365da8ae-8f37-11e8-97a3-9981fee9384a.jpg)

**Comment by gilbertohasnofb** [comment]
> Yesterday I tried making a 5 segment cord (similar to the mike cord) and used the mike cord texture to test the look. I had it sag slightly in the middle and narrowed the plug end that would plug into the panel. I assume it plugs into the panel?

That doesn't look bad at all! Do use the mike texture for now and later we can duplicate it if we stick with your solution. And yes, it plugs into the panel, perhaps a tiny bit higher than where you put it from what I can see in the photos posted before.

> I think with a decent x and y rotation centered at the panel plug location you could match the yoke rotation close enough. 

Great!

> The problem was the forward and back motion of the yoke. Either we use ??? to stretch the cord (same way we do the tie-downs or the original rescue helo rope, or I remove the tapered end and translate the rope end closest the panel into the panel which you can't see anyway. That would require a bit of x/y rotation on that end to match the elevation and lateral movement of the sag when it moved in and out, that might look cheep and funky.
> Any comments or suggestions?

I don't have an opinion in what option to try, please try whatever you feel will work better without too much pain. I completely agree with you that this isn't visible from the default angle (just the copilot's one, but barely) so we don't need to go overboard simulating a super precise string. I think you are excellent at judging the pain/gain ratio and coming up with very satisfactory solutions :smiley:

**Comment by onox** [comment]
> You probably could, but I don't think it worth the pain or the overhead. Those ropes are segmented. I think the aircrane's is 30+ segments. Then the math behind it to do what you want.
>
> Yesterday I tried making a 5 segment cord

If it's only 5 segments, the amount of computation needed to simulate it should be limited?

**Comment by wlbragg** [comment]
5 segments version was for a more simple rotate and translate animation. To do it justice and make it look really cool I think I would do a segment per coil or something close to that. You could potentially get some stretch out of it that way as well.
But the math logic to manipulate the segments would be the difficult part, at least for me.

**Comment by wlbragg** [comment]
@gilbertohasnofb OK, I think this is done. Please review.

**Comment by gilbertohasnofb** [comment]
@wlbragg Looks really good, this is such a clever solution. I pushed the new texture.

**Comment by gilbertohasnofb** [comment]
@wlbragg Just want to say once again how fantastic your solution is. I thought this issue would be nearly impossible to solve easily and it is looking so good. Even the compression of the texture looks natural given that we are modelling a cord like this. Bravo!

**Comment by gilbertohasnofb** [comment]
@wlbragg small bug: the cord is not being hidden when the yoke is hidden

**Comment by wlbragg** [comment]
Done

**Comment by gilbertohasnofb** [comment]
@wlbragg What do you think if we would remove the shadow effect from the yoke's PPT cord and from the yoke cylinder (the main bar connecting the yoke to the cockpit)? Sometimes they go 'randomly' darker and that doesn't look too good, and I suspect that's the shadow effect getting crazy on rotating and moving objects.

**Comment by wlbragg** [comment]
@gilbertohasnofb done.

**Comment by gilbertohasnofb** [comment]
Perfect, much better!
