### ISSUE TITLE
Improve Avionics Switch and Autopilot Circuit Breaker

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1122]
![image](https://user-images.githubusercontent.com/10434911/41193248-6c3d2a84-6c01-11e8-891d-e5aa6118aa86.png)

Our current switch and breakers look like this:

![image](https://user-images.githubusercontent.com/10434911/41193271-a917b9ce-6c01-11e8-82ba-6dd94cb04d45.png)

The part which could stand improvement is

![image](https://user-images.githubusercontent.com/10434911/41193274-bbfeec74-6c01-11e8-8410-8ffd530d4b20.png)

- Make a hole in the avionics switch face - currrently it is solid
- Add the autopilot circuit breaker's unique head

![image](https://user-images.githubusercontent.com/10434911/41193377-d81dc8f2-6c02-11e8-98fe-f01a83200293.png)

You can see more in 1080p at https://www.youtube.com/watch?v=IP2PIjqf-Wc

**Comment by gilbertohasnofb** [comment]
> Add the autopilot circuit breaker's unique head

@legoboyvdlp The disposition and look of the circuit breakers vary wildly from aircraft to aircraft, with each of my reference photos of the model P having a different layout. We did use some specific reference for the breakers but I can't remember where from. But I am fine with the current autopilot breaker.

> Make a hole in the avionics switch face - currrently it is solid

That would look prettier, though if you look closely the hole is represented in the texture:

![fg](https://user-images.githubusercontent.com/5700795/41217014-7ef25fe8-6d4e-11e8-992a-17ef640bc527.jpg)

But if @wlbragg wants to dig a proper hole in that model then I am fine with that by all means :smile:

**Comment by legoboyvdlp** [comment]
It might be rather difficult to do it without issues, but if it is possible it would be nice :)

**Comment by wlbragg** [comment]
OK, I made the avionics switch more like the one indicated here. It has a whole punched out and is re-textured to it's original texture. So @gilbertohasnofb this is another object to potentially correct the light map on.

![avi](https://user-images.githubusercontent.com/11069680/43105121-62171a50-8e99-11e8-820b-8e6684a66327.jpg)

**Comment by wlbragg** [comment]
It actually is textured to the same texture.
See...

![avi](https://user-images.githubusercontent.com/11069680/43109219-442ced6e-8eab-11e8-9240-185215055232.jpg)

**Comment by legoboyvdlp** [comment]
Yes - I meant the entire base of the switch (not just the circle but the hexagon) actually - if you compare it to the image I posted originally, it definitely looks much more metallic grey while this one looks a bit like white plastic. I also am not sure about the "dirt" on the bottom half of the texture, as the switch is so small it just shows up as a brown black lowres blob :joy:

**Comment by gilbertohasnofb** [comment]
@wlbragg Ok I tried improving the texture but this is a bit difficult because the model isn't matching the reference photo. I adjusted the metallic colour as to match the switch itself but I think we can do with some improvements to the model. Here is my suggestion; above is the current model, below is how to improve it. I think we need to add a 'ring' around the base before the base starts to become the inverted cone in which the switch is connected to. Look at the cross sections (righthand side of the image):

![image](https://user-images.githubusercontent.com/5700795/43230231-64d29892-905f-11e8-9c13-f7d69b54dc09.png)

This is what I currently have:

![image](https://user-images.githubusercontent.com/5700795/43230249-78e824e6-905f-11e8-9e19-81a5b1a6103e.png)

By the way, I did notice that the base of the circuit breakers look very black. Is that intentional or do we have some mapping issues? I don't remember them being like this before.

**Comment by wlbragg** [comment]
The avionic switch just needed remapped after your texture change. The breaker bases needed a remapping as well, they were using the wrong texture.
All should be good but they all will need new AO and light map.

**Comment by gilbertohasnofb** [comment]
> The avionic switch just needed remapped after your texture change. The breaker bases needed a remapping as well, they were using the wrong texture.

That looks good! I think this is job done :smile: 

> All should be good but they all will need new AO and light map.

Yeah, we will possibly need to redo the AO and light maps for the three interior textures. Let's just finish with any modelling issues and then we move on to that.
