### ISSUE TITLE
Improve KMA20's marker sensitivity toggle animation

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#1154]
Improve KMA20's marker sensitivity toggle animation. All other toggles can be flicked either by clicking above or below them (there are two hidden squares as click spots) but also by hovering the mouse above the toggle and moving the mouse wheel up and down. The marker sensitivity toggle does not behave this way as it has a more complex behaviour. Ideally they should all be consistent.

**Comment by wlbragg** [comment]
@gilbertohasnofb this switch is a bit different because the toggle down has a mod-up to it. In other words it is made to snap up when switched down. It is not made to stay down. It is a test mode. All the others are pure toggles that are on or off. I'm not sure it would work correctly with the same knob animation as the rest of them.

**Comment by gilbertohasnofb** [comment]
I see. Ideally the toggle would work with the mouse wheel at least between the up and middle positions. Switching it down could for instance activate a small script which would hold the button down for like 1 or 2 seconds before returning it to normal. But this might be too much work for such a small thing. What do you think?

**Comment by gilbertohasnofb** [comment]
The answer possibly lies somewhere between never and incredibly seldom to the point of nothing.

**Comment by wkitty42** [comment]
On 07/30/2018 01:22 PM, wlbragg wrote:
> I guess I would like to know how often this switch is used?


at least every time you're doing the pre-startup checks when you check to make 
sure you don't have any burned out bulbs... one might also use it in the air if 
they're expecting to be over a marker and they're not seeing/hearing the 
indicator...

**Comment by gilbertohasnofb** [comment]
@wkitty42 is that on the official checklist or is it something that people 'should' be doing?

**Comment by wkitty42** [comment]
On 07/30/2018 02:46 PM, Gilberto Agostinho wrote:
> @wkitty42 <https://github.com/wkitty42> is that on the official checklist or is 
> it something that people 'should' be doing?


official checklist? that thing in the POH that no one ever looks at and follows? 
i don't know... i've never looked at it ;)

i do know about checklists, though... had to actually file them once upon a 
time... had to do some when i was working with 18-wheelers... eg: if your brakes 
went out because you didn't check them before leaving on a trip, you ate the 
bill for fixing them and anything else that might have been damaged because they 
did fail...

but anyway, yeah, you have to check your external lights so i can't see not 
checking your internal ones, too... doesn't matter to me, really... i was just 
answering the raw question that was posed :)

**Comment by gilbertohasnofb** [comment]
> official checklist? that thing in the POH that no one ever looks at and follows? i don't know... i've never looked at it ;)

Oh, I think you are wrong on this one, I really think that most pilots take a quasi-religious approach to the checklist from what I know. 

About the checklist and the POH, I checked for the term 'marker' and there are only two mentions, one about the type of the equipment for the marker indicator and other locating it in the panel layout. There is nothing about requiring it to be tested as part of the procedure.

**Comment by wkitty42** [comment]
i was being facetious about folks not looking at the POH or checklist :wink: 

i didn't say it was "required" but yeah, i hear what you're saying... it just seems weird that they'd tell you where it is and not tell you to toggle the switch to test that all three of the marker lights come on when the switch is held... anyway, whatever :lol:

**Comment by gilbertohasnofb** [comment]
once you mentioned it I also imagined it would be part of the checklist, at least under some generic item like 'check all radio lights' or something like that but they have nothing.

**Comment by wlbragg** [comment]
@gilbertohasnofb I added the knob animation to the Hi and Low portion of the "marker sensitivity". You can use the mouse wheel on Hi and Low, you must use the pick on the lower test label to test.

**Comment by gilbertohasnofb** [comment]
That's a nice solution. I tested it and the only issue is that the angle of the toggle object is too large in the HIGH or TEST positions. Compare it to all other toggles.

**Comment by wlbragg** [comment]
> issue is that the angle of the toggle object is too large in the HIGH or TEST positions

@gilbertohasnofb  this is done.

**Comment by gilbertohasnofb** [comment]
Thanks, I tested it and it looks perfect
