### ISSUE TITLE
Low Voltage LED colour

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1160]
Hi,
I just pulled the 172 improve-3D-objects:

![image](https://user-images.githubusercontent.com/10434911/43676977-a0d2e6ae-97f2-11e8-9205-6c48e557ecfc.png)

![image](https://user-images.githubusercontent.com/10434911/43676982-b59e0b0e-97f2-11e8-9f4f-14aadd842729.png)

With the white cockpit (D-EEQA etc), the low voltage LED is also too white - almost pink.

With the black cockpit, it looks fine. 

![image](https://user-images.githubusercontent.com/10434911/43676989-cb0908d6-97f2-11e8-9143-193db9ea9759.png)

The LOW VOLTAGE legend should also be added to the other cockpits.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp when we make large changes to textures, I only make them to the 4X-CHV texture so that we can test it first and make all adjustments before syncing it with all other liveries. At the moment there are plenty of textures missing for all other liveries but that's because we are still working on them.

**Comment by legoboyvdlp** [comment]
Ah, ok - apologies!

**Comment by gilbertohasnofb** [comment]
No need to apologize, lego! It's good that you are paying attention to potential bugs, misreports are part of the job :wink:
