### ISSUE TITLE
Heading Bug Misaligned

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1161]
![image](https://user-images.githubusercontent.com/10434911/43677078-26404128-97f4-11e8-85ec-2176022d1e6c.png)

With the heading bug tooltip saying 180, you would expect the heading bug to be directly on the "S" - it is about 2 degrees offset, you must set 178 or so to have it on the "S". I think the heading bug is misaligned?

**Comment by gilbertohasnofb** [comment]
I don't think so, @legoboyvdlp. Facing directly forwards and looking directly at the gauge the bug looks quite well aligned for me:

![fg-3](https://user-images.githubusercontent.com/5700795/43678912-e1cbda78-9813-11e8-9715-f9c12b4d0c38.jpg)

When looking from the pilot's perspective, the bug looks a bit lower because it is a fraction more forward than the gauge itself. But also we can't really think of 1 degree precision with these instruments, even the scale itself goes from 5 in 5 degrees. IMO this is an `invalid` or `won't fix` but I will let others join in before closing this.

**Comment by wkitty42** [comment]
On 08/04/2018 01:30 PM, Gilberto Agostinho wrote:
> When looking from the pilot's perspective, the bug looks a bit lower because
> it is a fraction more forward than the gauge itself.

i think it is a perspective thing, too... i started to write such when i was 
through earlier but decided not to as i may not have been seeing things clearly...

if you move the view down level with the center of the guage, the pointer looks 
ok... if you move the view below the center of the guage, the pointer looks too 
high... this is normal and i think is known as parallax...

parallax is where if you look at an object with both eyes, it looks like it is 
in position X... if you close one eye, the object appears to move to position Y 
and if you close the other eys, the object appears to move to position Z...

**Comment by wlbragg** [comment]
I think it is good, looks like perspective is an issue here.
