### ISSUE TITLE
Autopilot Panel Lighting

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1162]
With the radio knob set to the minimum position shouldn't the autopilot's display also be fully bright (not the knobs)?

![image](https://user-images.githubusercontent.com/10434911/43677354-94016a30-97f8-11e8-81d1-316706ce8bef.png)

**Comment by gilbertohasnofb** [comment]
Confirmed. Here is a comparison between RADIO LT 0% and 100%

![fg-1](https://user-images.githubusercontent.com/5700795/43678950-8fe62cb2-9814-11e8-88c6-97ec5f38b873.jpg)
![fg-0](https://user-images.githubusercontent.com/5700795/43678951-91cf5936-9814-11e8-96f1-4819867b7807.jpg)

@wlbragg could this be related to some of the effects we have on these digits? I remember having spoken with you about some similar problem in the past.

**Comment by gilbertohasnofb** [comment]
@wlbragg This bug doesn't have anything to do with shadows. At night (when shadows should not matter) this is how the radio stack looks like. Notice how the AP has different brightness at 0% and at 100%:

![fg-0](https://user-images.githubusercontent.com/5700795/43679585-291cdd0e-981f-11e8-9296-5c46e4e79165.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/43679586-293849cc-981f-11e8-9bb1-e80502b4cdfc.jpg)

> I am not sure why we don't want bright light to affect the led lights brightness, same as we do for all the other lighting schemes? I think it should.

Not sure I understand what you mean. Concerning that issue, I don't think bright light affects the digits, rather shadows are making them darker which is definitely weird to me.

**Comment by wlbragg** [comment]
>Notice how the AP has different brightness at 0% and at 100%:

OK, I see that and will investigate.

> I don't think bright light affects the digits, rather shadows are making them darker which is definitely weird to me.

I could have said that better.
What I mean is the led on the radio equipment should be less brilliant (or maybe more accurately they should exhibit less contrast with the surrounding objects). in full sun than in shadow. Our shadow effect does just that, so does the overall effect of model-interior without the shadow cube code included.
I think you and I talked about removing the shadow cube effect from the led digits on the 165's.
Do you still think we should? If so then we should do it to all the led's on all the equipment in the stack.
I think I would like to see a comparison with and without before I would be on board with that.

**Comment by gilbertohasnofb** [comment]
Thanks for taking a look at this bug. Concerning the shadow thing, let's move this discussion to the correct issue, I will reply there.

**Comment by gilbertohasnofb** [comment]
@wlbragg do you think you could take a look at this so we could incorporate a potential fix into that PR?

**Comment by wlbragg** [comment]
@gilbertohasnofb yes, but I am afraid this is going to be the same can of worms as #1149

I have them both pinned to my browser bar and will look at them as soon as I finish the other stuff. IE: the ELT antenna and mapping issue of the tail section's connection to the fuselage.

**Comment by gilbertohasnofb** [comment]
> but I am afraid this is going to be the same can of worms as #1149

You know these things better than me but I dare to say that these are very different issues. 1149 has more to do with the code of the electrical system interacting with the light intensity code, and there might be a ton of reasons for the delays on the systems, etc. But this one here seems more to do with the 3D object itself and how the effects are applied to it, and it is quite similar to another issue we previously had and which is already fixed: https://github.com/c172p-team/c172p/issues/770

> I have them both pinned to my browser bar and will look at them as soon as I finish the other stuff. IE: the ELT antenna and mapping issue of the tail section's connection to the fuselage.

No rush, we are doing excellent progress!

**Comment by wlbragg** [comment]
@gilbertohasnofb after rereading this thread I was wrong

>the led on the radio equipment should be less brilliant (or maybe more accurately they should exhibit less contrast with the surrounding objects). in full sun than in shadow. Our shadow effect does just that, so does the overall effect of model-interior without the shadow cube code included.

The shadow effect applied to the digits has the opposite affect of what it should do to an emissive source, it shadows them and dulls them as it does to surfaces. So it shouldn't be applied to an emmisive source.
As far as the model-interior shader, I'd have to verify what that does to the same emissive source.

So you were correct, the shadow effect was having a bad effect on the LED and shouldn't be used on it.

Now the issue at hand...

>but I dare to say that these are very different issues. 1149 has more to do with the code of the electrical system interacting with the light intensity code, and there might be a ton of reasons for the delays on the systems, etc. But this one here seems more to do with the 3D object itself and how the effects are applied to it,

I'm afraid the issue is in the electrical, or more accurately with the filter or whatever code is used to set the brightness at 0% the same as it is supposed to be at 100%. This might have to do with that code. Finding it and following it is not real intuitive I think.

> the 3D object itself and how the effects are applied

That's just it, it should be the same, right?
At 0% it should be in daylight mode, >0 it should be filtered through the instrument rheostat. !00% with instrument rheostat and 0% should be the same value. The question is, why aren't they.

**Comment by gilbertohasnofb** [comment]
> Now the issue at hand...

Yeah, I understand what you are saying. I was checking the code for that other issue I mentioned but that was something different, that was just a tweak of the max intensity and colour hue, nothing related. But the problem is that right now the AP is quite difficult to read in daylight. I don't remember this being the case before, maybe it would be possible to track down the commit that changed that, maybe the answer could be there. 

This weak digits in the AP look so ugly in our pretty cockpit! 😭

**Comment by wlbragg** [comment]
@gilbertohasnofb this is fixed, but, I think because of the flow of the code logic it may exhibit small delays at various moments, similar to the other issue.
