### ISSUE TITLE
Ground shadows just a few metres below the aircraft in flight in replay

### ISSUE THREAD

**Issue by HHS81** [c172p-team/c172p#1212]
In replay modus the ground shadow ist jsut a few metres below the aircraft.
 Instead it should be on the ground.
You can see it here in the video: [https://www.youtube.com/watch?v=LfCcw6t04k0](https://www.youtube.com/watch?v=LfCcw6t04k0) at 0:21 and the following seconds.

c172p from fgdata, pulled yesterday, matching FlightGear bin (218.4.0)

**Comment by gilbertohasnofb** [comment]
@HHS81 I can't reproduce that. I am using our `master` branch and FG 2018.2.2 (I'm waiting for the PPA to be updated for version 2018.3.1). Is anyone in our repo on version .3 or .4 so that we can try to reproduce this?

**Comment by legoboyvdlp** [comment]
I'm on 2018.3 (compiling 2018.4 at the moment actually!) I'll give it a test in the morning.

**Comment by legoboyvdlp** [comment]
I've not had a chance to test - my compile failed for some reason i'm still trying to determine, so I'm still trying to troubleshoot that, apologies.

**Comment by gilbertohasnofb** [comment]
@wlbragg I think that's possibly just a side effect of how the shadow works in FG. I have not tested it, but I imagine our shadow would also look dreadful when cast into a mountain slope, since the shadow is a flat horizontal surface (correct if I am wrong).

**Comment by wkitty42** [comment]
do we (still?) have 2D shadows? i remember some conversation about shadows way back when this project got started...

**Comment by gilbertohasnofb** [comment]
Originally we used a simple 2D fixed shadow (just an image) but then we moved to a better solution: using a low-poly model of our aircraft (which is hidden from view) we can project its part and dynamically create a shadow, so that at low angles the shadow gets stretched as it should. But I think this is still done by projecting this hidden model into a flat plane, which then is placed just above the ground (to avoid z-conflict). This doesn't always work and in many situations I have still observed some z-conflict of our shadow with the ground. 

So because of this implementation, any terrain that is not flat should end up hiding part of the shadow.

**Comment by wlbragg** [comment]
Oh wow, I totally missed the "In replay mode" I think I can track that down and fix it. I imagine it's a missing or incorrect signal in the replay code.

**Comment by wlbragg** [comment]
Could someone that can actually use the flight recorder verify the fix worked?

**Comment by legoboyvdlp** [comment]
Sure, will do.
