### ISSUE TITLE
Flap lever sound: should only sound when lever position changes

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#1234]
If you currently drag the flap lever upwards when flaps are retracted or downwards when they are fully extended you still get the lever clicking, even though the lever doesn't move at all?

The same occurs with the [ / ] keys.

**Comment by legoboyvdlp** [comment]
e.g. 
![image](https://user-images.githubusercontent.com/10434911/48218250-5ae45580-e381-11e8-8f4b-32e72c53732b.png)

![image](https://user-images.githubusercontent.com/10434911/48218260-62a3fa00-e381-11e8-918a-0a34d021ebb0.png)

**Comment by gilbertohasnofb** [comment]
What do you mean? If you drag the lever then surely the lever moves, right?

**Comment by legoboyvdlp** [comment]
Yes - but the sound occurs when you drag the lever up when its already at the minimum position or down when its already at the maximum position.

**Comment by gilbertohasnofb** [comment]
Oh I see, you are talking about the extreme positions. This is a big with
FG, all our switches and levers suffer from the same. We previously decided
not to try to fix this on our side as we believe this should be addressed
in the core code. You could raise this point in the dev list if you'd like,
that would be excellent.

**Comment by legoboyvdlp** [comment]
What precisely is the bug and what behaviour do we want instead?

**Comment by onox** [comment]
IIRC I think the bug is that FG supports a mode called 'in-transit' but it only works well for floats (see the flaps motor sound). It doesn't work well for integers, because they change instantly (from 0 to 1 or 1 to 2) and thus it plays the sound for maybe 1 frame instead of till the end of the sound file.

So to work around this we have this `c172p.click()` function.

We seem to be overriding `controls.flapsDown` in https://github.com/c172p-team/c172p/blob/4f5bb3450c254c4c2d51e2a4e5493a994cf85ddc/Nasal/electrical.nas#L500-L504 I think you can try to compare the current value with `v` and if they're different then you execute `c172p.click("flaps");`.

**Comment by gilbertohasnofb** [comment]
@onox Comparing `v` would not work since `v` does not show the current flap position. `v` is an argument for the direction and it is either `1` or `-1` which is used in `Models/Interior/Panel/Flaps/flaps.xml` to choose the direction of the movement of the lever. I fixed the issue in the opened PR by simply removing the `c172p.click()` from the flap motion function and using an `in-transit` parameter for the sound. Seems to work well.

**Comment by onox** [comment]
It does? OK, using `in-transit` is a better solution then.
