### ISSUE TITLE
Cannot change throttle position with generic protocol

### ISSUE THREAD

**Issue by giomasce** [c172p-team/c172p#1278]
I tried to implement the Arduino generic protocol as indicated in http://wiki.flightgear.org/Howto:Use_Arduino_with_FlightGear, but it does not work. In particular, I cannot change the throttle lever position in the C172 (it works for other planes). I believe that the problem is that the `/controls/engines/engine/throttle` is continuously rewritten by some other code for the C172. I believe that for basically all other aircrafts that property is considered an "input" property, not to be modified by the engine code, while the C172 breaks this assumption. Is it possible to have it fixed?

Thanks!

**Comment by dany93** [comment]
There is nothing to fix, that's normal.

The c172p has two possible engines (one at a time) for 160 and 180 hp.

> (it works for other planes)

Probably not, your code is too restrictive. `/controls/engines/engine/throttle` can not work on every FG aircraft because it controls only the first engine[0].

I've never done this. I only use the Joysticks code, please look at it and see the` fgdata/nasal/controls.nas`. (line 68 on my version)
By reading this code, a clue : I would rather set`/controls/engines/throttle-all`. This one should work on every FG aircraft. Attention: Its values must be from -1 to +1.

Otherwise, on c172p, see
`/controls/engines/engine/throttle``
`/controls/engines/engine[1]/throttle
for separate control of one engine at a time,
and
`/controls/engines/current-engine/throttle`
For any c172p engine configuration.

**Comment by giomasce** [comment]
Yes, my code only controls the first engine, but on any aircraft it is enough to change `/controls/engines/engine[X]/throttle` to set throttle for engine X. I believe it would be nice if C172 followed the same pattern. Thanks for the workaround, anyway.

**Comment by dany93** [comment]
That's not a workaround. Usual joysticks (almost every joystick) control the engine(s) by this property. Joysticks with several throttle levers are minority.

For the c172p, people does not need to know or wonder if they have to use the engine [0] or [1].

**Comment by giomasce** [comment]
Ok, thanks.

**Comment by gilbertohasnofb** [comment]
@dany93 can we close this?

**Comment by dany93** [comment]
@gilbertohasnofb,
 Yes
