### ISSUE TITLE
Strong pitch oscillations at rest, Brakes "ON", with pure crosswind 

### ISSUE THREAD

**Issue by dany93** [c172p-team/c172p#1297]
Connected to:
- this remark by @algefean https://github.com/c172p-team/c172p/issues/1130#issuecomment-399561812
- this one, https://github.com/c172p-team/c172p/issues/1130#issuecomment-403204924
 and 
- this issue (description, investigation and circumventing solution) in JSBSim https://github.com/JSBSim-Team/jsbsim/issues/89

Very rare, we were the first ones to notice it. It happens with a pure crosswind (less than +/- 1 deg, about), aircraft at rest, brakes "ON". Every JSBSim aircraft is potentially affected, but our C172p is more sensitive due to its implemented gear damage possibility.
All the more unlikely that this occurence is almost impossible in flight.

The conclusion was that it was due to an imperfection and a divergence in a JSBSim calculation.

After careful investigation, @bcoconni found no true solution, but he proposed a circumventing which works. However, this change is not in the JSBSim core code, it has to be applied to every affected aircraft. Fortunately, the change is very easy to add in.

**Comment by wlbragg** [comment]
Great, I think I have seen this in the j3cub. I had no idea what was causing it as it so rarely happened, but when it did it was very strong. It makes sense that the cub also exhibited this issue.
Can this be tested by introducing a crosswind to my version of the c172p or the j3cub before and after the fix is applied?

**Comment by dany93** [comment]
Easy to test in the simulator.

You have both versions ready for the c172p (before and after this PR).
You have to add the code in the J3Cub FDM (both CLadot and Cmadot).

Aircraft at rest on the runway, **brakes "ON"**. Even with the engine stopped. Just set a crosswind accurately perpendicular to the aircraft.

Example:
KSFO, runway 10L.
The wind direction is in true heading (not magnetic).
- Read the aircraft **true** heading: 117.89 deg (Internal Properties).
- Environment > Weather > Manual configuration: Set a wind, dir = 117.9 - 90 = 27.9 deg, 3 kt is enough (10 kt is worse). For  preferably 0 and 500 ft elevation.
If the aircraft slightly yaws, adjust the wind heading accordingly.
You can check the wind-from-heading and -speed in the Internal Properties (environment/).

**Comment by bcoconni** [comment]
@dany93 wrote:
> The conclusion was that it was due to an imperfection and a divergence in a JSBSim calculation.
>
> After careful investigation, @bcoconni found no true solution, [...]

I would like to mitigate that statement because it is quite inaccurate.

As I have shown in https://github.com/JSBSim-Team/jsbsim/issues/89#issuecomment-473670031, the computation of aerodynamic forces **must not use** the total velocity that includes the span-wise velocity. I explained that this was not conforming to the laws of physics (namely the good old Kutta-Jukowsky theorem) and I also ran a numerical aerodynamics simulation to support that statement.

JSBSim overreacts to that modelling error and indeed I investigated if JSBSim could mitigate it by preventing the moments from diverging to infinity. As @dany93 mentioned, I could not come to a solution for that and this modelling error continues to blow to the face of aircraft modellers (and users alike). But this should not hide the fact that **the actual error is in the aircraft model, not in JSBSim**.

JSBSim is a numerical simulation software and as such it obeys to the ["Garbage In, Garbage Out" law](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out): if the aircraft model is erroneous then the simulation will be erroneous. Retrospectively I think it is a good thing that JSBSim exposes the error by letting moments diverging rather than hiding it and leaving modellers in the false comfort that their model is accurate.

**Comment by dany93** [comment]
> I would like to mitigate that statement because it is quite inaccurate.

> the actual error is in the aircraft model, not in JSBSim.

Sorry @bcoconni for my misunderstanding, and thank you this additional information.
And thank you once more for having investigated and found a solution to avoid this behavior. 

If I understand well, changing this in [aeromatics](http://jsbsim.sourceforge.net/aeromatic2.html) would be the best way.

**Comment by bcoconni** [comment]
> Sorry @bcoconni for my misunderstanding, and thank you this additional information.

No need to apologize as there was no offense taken :smiley:. I just wanted to set the facts straight so that aircraft modellers know they have potentially something to fix in their model and they must not wait for a JSBSim fix that will never happen anyway.
> If I understand well, changing this in `aeromatics` would be the best way.

Correct and I guess this should be documented somewhere as well. Not everyone uses aeromatic to start their model. Another topic to my (quite) long TODO list.

**Comment by wlbragg** [comment]
I read the related issue in the jsb project, interesting, thank you all for digging into this and resolving the issue.

**Comment by wlbragg** [comment]
@dany93  I will try to get this tested and merged later tonight.
