### ISSUE TITLE
Amphibious gear breakers always visible

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1299]
I really don't know how this slipped through the cracks. It was obvious when you were in default gear configuration.

I am really annoyed I didn't see this when we had the chance to get it in 2019.1.

Even after all this time I am still not sure when and where we are allowed to backport bug fixes?

**Comment by gilbertohasnofb** [comment]
> Even after all this time I am still not sure when and where we are allowed to backport bug fixes?

Me neither, though normally we stipulate a final date for the merge into FGData and that is long gone; but at the same time, it seems the release is super delayed. Do you know when the next release will be out? The website still only has the 2018.3 as the latest version. Maybe we could try sending a personal message to Stuart asking for this, particularly since this fix is only 4 lines long? But other than that I really don't know.

**Comment by wlbragg** [comment]
@gilbertohasnofb thank you for merging, I'll contact Stuart and see what he says.
