### ISSUE TITLE
glass effect over the gauges

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#13]
3D11 - can put "glass effect" over the gauges. What do you think ?
- Gilberto: that would be great!!

**Comment by stuartbuchanan** [comment]
Hi Guys,

Could I suggest not adding the glass effect over the gauges, or at very least making it toggled by a separate property?  In my experience you don't see any reflection in gauges - even in my microlight (which is open cockpit) I don't notice them because the interior of the aircraft is so much darker than the outside.

-Stuart

**Comment by onox** [comment]
@stuartbuchanan Is there any harm in adding the glass effect?

**Comment by gilbertohasnofb** [comment]
@stuartbuchanan I think the idea was to use Thorsten's new effect, and I am pretty sure it would be active only if the model shader would be set at max.

**Comment by stuartbuchanan** [comment]
Hi Gilberto, onox,

@onox: there's probably a bit of a perf impact simply due to the number if additional objects with the effect but if won't be massive. 

@Gilberto: I hadn't realised you were talking about Thorstens shader - I thought you were talking about Helijah's which just uses a cube-map of the sky and hence is very unrealistic.  I expect that you'll find that implementing Thorsten's shader on the instruments will result in almost no reflections because of the angles involved and the darkness of the cockpit. 

-Stuart

**Comment by gilbertohasnofb** [comment]
Hi Stuart,

> I expect that you'll find that implementing Thorsten's shader on the instruments will result in almost no reflections

If that would be the case, then we can see if it worth to be done, but I guess we would only know for sure if we tried to implement this. My opinion is to give it a shot and make some tests (also check for any performance drop) and then decide if it's worth it or not.

Cheers!

**Comment by gilbertohasnofb** [comment]
Guys, could we consider this for the 3.6 milestone or better leave it for after? How easy would it be to implement Thorsten's glass effect?

**Comment by wkitty42** [comment]
i see no problem with it if it can be put in easily and be ready to go with no problems... there's still a number of other issues that need to be fixed before the freeze if we can get them done... i don't think we want to see :ahem: ""the microsoft way"" where features are implemented and bugs are left unfixed :wink: :laughing:

**Comment by gilbertohasnofb** [comment]
Sure, let's not push to have even more features just for the sake of having more features! But if this is easy and someone has the free time, then why not? :smile:

**Comment by wkitty42** [comment]
agreed :)

**Comment by gilbertohasnofb** [comment]
I just loaded the Cap10C and the glass effect over the gauges looks pretty good to me, nicer than what we currently have. Does anyone know if that's the new effect by Thorsten or some older effect?

**Comment by onox** [comment]
Cap10c is one of those many unmaintained aircraft, thus no Thorsten's ALS glass shader as far as I could see in the code.

Have you read https://github.com/Juanvvc/c172p-detailed/issues/13#issuecomment-102785210?

**Comment by gilbertohasnofb** [comment]
> Have you read #13 (comment)?

**Comment by gilbertohasnofb** [comment]
> Have you read #13 (comment)?

Yep, I read it, but I disagree with that, the effect in the Cap10C looks quite pleasing to me. And a lot of images I have seen show reflections in the gauges, such as this:

![](https://c1.staticflickr.com/5/4104/5089018343_37ea132a4b.jpg)

**Comment by wlbragg** [comment]
Stuart may have been referring to "from a pilot perspective". I would think by design any newer aircraft would implement some type of anti-glare screens.

**Comment by gilbertohasnofb** [comment]
> Stuart may have been referring to "from a pilot perspective" as in most instruments are strait in front of you without angle for glare.. 

Yeah, I guess it diminishes a lot from the pilot's perspective, but I think one can still tell that there is a glass in front of the instrument because of some reflection. See these images for instance:

![](http://www.aviationspectator.com/files/images/Cessna-172-28.jpg)

![](https://farm7.staticflickr.com/6195/6066184333_b3b1cc4a55_b.jpg)

> I would think by design any newer aircraft would implement some type of anti-glare screens.

Which is not our case anyway :wink: 

Anyway, just one idea, I personally like the effect, but if you guys think it's unrealistic then let's just skip it, no biggie.

**Comment by onox** [comment]
You can try to add it. But you need transparent glass objects in front of all the instruments and attach them to the `Models/Effects/exterior/exterior-glass-reflection.eff` effect.

But I think we should focus on more important things right now :stuck_out_tongue_closed_eyes:

**Comment by gilbertohasnofb** [comment]
> But I think we should focus on more important things right now :stuck_out_tongue_closed_eyes:

Agreed.

**Comment by wlbragg** [comment]
>Which is not our case anyway

Yes, didn't mean to imply otherwise.

**Comment by stuartbuchanan** [comment]
Hi Guys,

Yes, I meant from the pilots viewpoint.

All the images here are from a eyepoint significantly lower than the normal
pilot viewpoint.  The last one (which shows only a small level of
reflections) has still got an eyepoint at the same height as the
glareshield.  I'm pretty sure that from an eyepoint 12 inches higher, a
high wing aircraft is going to have almost no reflections, purely from the
geometry of the reflections, though I don't have time right now to look for
photos myself.

A low-wing aircraft will be slightly different, as there will be more light
in the cockpit interior.

-Stuart

**Comment by gilbertohasnofb** [comment]
@stuartbuchanan I do understand your point Stuart, but I think that it's rather a question of degree. So while I agree that those photos above show a very strong effect due to the angle, I believe that a very weak effect could look very nice AND realistic. Look, it has been almost a decade since the last time I've entered a Cessna cockpit, but what I am thinking is something similar to this image below (which is a product for a commercial flight simulator):

![](http://www.mutleyshangar.com/reviews/ag/172RG/img/14%20-%20Detailed%20Panel%20View,%20Left%20Side.jpg)

Notice how the manifold pressure and the RPM indicator have some glass effect on them, but very weak. Other instruments also show the effect, but extremely subtle. Wouldn't you say this look more realistic than no effect at all?

Anyway, as @onox wrote, we have more important things to work on right now so this is by far a non-priority issue :smile:

**Comment by gilbertohasnofb** [comment]
Here is a nice example of a very good looking glass effect over gauges on FlightGear:

https://www.youtube.com/watch?v=Dec1y_0WrhQ (from around 0:13)

**Comment by wlbragg** [comment]
Not bad, if no one beats me to it, I'll have a look and see how their doing it.

**Comment by stuartbuchanan** [comment]
Hi Guys,

I think that video really shows what I see as the problem with these glass
effects, which I mentioned before.

Assuming the dials are set vertically, the angles and reflection in the
geometry implies that there is a bright scene of the ground and sky behind
and slightly _below_ the pilot eyepoint, yet obviously that's where the
pilot and the bulk of the aircraft is!  Furthermore the source of these
reflections isn't going to be particularly bright, particularly compared to
the view outsides.  My brain keeps on thinking there's something wrong with
the scene because it's no self-consistent.

In a high-wing Cessna there would be even less reflection in the instrument
dials because of the combination of the high wing and window-line.  From a
pilot eyepoint, the reflection would be of the pilot's lap, and for that to
be in direct sunlight and therefore bright enough to cause a reflection
you're heading straight towards the sun with the sun at a moderately high
angle (say 60-80 degrees) so it's not obscured by the panel or the wing.

Reflection of the sky and the outside world is simply unrealistic unless
you've got some truly weird viewpoint - say from the side and slightly
below and behind the cockpit with the door open!

-Stuart

**Comment by gilbertohasnofb** [comment]
@stuartbuchanan I think you do have a point and that the effect in the video is a bit exaggerated, but from the photos I have seen one can always tell that there is a glass in front of the gauges due to a small amount of reflection. For an example of how this could look like once implemented, see this screenshot I previously posted (from another sim) which does look quite reasonable to me, the glass effect looks really good: https://github.com/c172p-team/c172p-detailed/issues/13#issuecomment-165092158

So perhaps it's really a matter of tuning the effect down to the barely noticeable, but still being there. @wlbragg do you think this would be possible?

**Comment by wlbragg** [comment]
I'd have to have a look to be sure, but my first reaction would be yes.

**Comment by HHS81** [comment]
@gilbertohasnofb  @wlbragg
The effect in the video is ugly (beside they are taking my work without any reference to me 😠 ).
It is ugly because like Stuart already said, as the reflections itself are wrong and too strong.

So we actually need the interior glass reflections, but the camera of the cubemaps should be on the panel at the height of the instruments, looking into the interior.
 Then we need a fresnel effect, like we have already on the fuselage-shader. Maybe the fresnel can be easily adapted on the interior glass reflections.

**Comment by gilbertohasnofb** [comment]
@wlbragg I still think this effect could look nice. We can try to make it very subtle, and we can also make it togglable via the aircraft menu just like the pilot model and shadows are. I can also totally live with this options being set to no reflections on gauges by default.

**Comment by gilbertohasnofb** [comment]
@wlbragg another option is to hardcode the effect directly on the gauge textures: http://wiki.flightgear.org/Howto:Glass_reflection_effect_for_instruments

But I still would prefer a very subtle true effect.

**Comment by wlbragg** [comment]
I don't mind looking at the feasibility of this, but I am a bit confused as to exactly what technique to look at.
It will make a difference as to how this fits with the rest of the effects definitions depending on the technique used.
So do we know exactly what technique were wanting to test or try?

**Comment by gilbertohasnofb** [comment]
@wlbragg I don't remember what effect was being used but some aircraft do have this gauge glass effect, though most of those use a very strong and ugly setting. We need to investigate what's possible with FG at the moment -- perhaps starting by asking Thorsten? -- and then test to see how it would look. The aim should be a super subtle effect such as seen in https://github.com/c172p-team/c172p/issues/13#issuecomment-165092158

**Comment by wlbragg** [comment]
Well this took all of about 10 minutes to do using the existing interior glass reflection and adding the glass mesh in Blender.
Not bad for 10 minutes worth of work.
I'll push a new branch with it later on tonight if you think were still interested!
https://www.dropbox.com/home/Public/fg/c172p/videos?preview=2018-06-29+16-21-42.mp4

**Comment by wlbragg** [comment]
I wasn't sure how this was going to work at the start so without any thought I made the glass from the recessed panel edges. I think I should instead make the glass fit the interior edge of the instrument case, would be a much better effect and more appropriate.

**Comment by gilbertohasnofb** [comment]
@wlbragg That link is broken for me, can you double check it?

**Comment by wlbragg** [comment]
OK, try it now.

**Comment by gilbertohasnofb** [comment]
Looks fantastic. Do you think we can tone down the effect by like 30% of what you have now?
