### ISSUE TITLE
FGAddon version - Unable to control c172 after take off in amphibious tutorial

### ISSUE THREAD

**Issue by camileck** [c172p-team/c172p#1321]
Hello, I have initially described the issue there: https://forum.flightgear.org/viewtopic.php?f=25&t=37372 but posting it here as well as per forum member advice. So I can control aircraft when on the water without any problems but as soon as I take off it seems that slip indicator takes only 2 positions - max right or max left and it is impossible to counteract on it with rudder as it immediately takes the opposite position. As soon as I fly over the land slip indicator and physics get back to normal and I can control aircraft as usual but if I return over the water it goes back to this strange behaviour what makes it impossible to control it.

**Comment by dany93** [comment]
Hello @camileck 

I don't see this behavior. Flying over the water, the slip ball reaction is normal, like over the ground.
This brutal slip ball movements happen only when the floats touch the water. Which is normal.
Do you see this when touching the water, or very close (less than about 2 meters high), or also at higher height above the water?

In the forum, you write 'when in amphibious tutorial'. In this case, I don't know, I've never used the tutorial.

**Comment by wlbragg** [comment]
Sorry I didn't see your post on the forum. I just tried it and it worked fine here as well. I am using the most current version of FlightGear next (a couple days old). I know it also works in "stable".
What your describing sounds similar to other buggy actions caused by an internal FG core issue of 2019.? versions.
What version of FG are you running?
What operating system?
Next step after we verify your version might be to paste your log here for us to look at.

**Comment by wlbragg** [comment]
What you describe is that "some" variable is being changed when the aircraft is over water. That is true, there is at least one variable we monitor to know when the aircraft is over water.
The problem is it sounds like that variable is triggering an action of another variable that it is not supposed to. That sounds like memory corruption. That is the 2019.x (garbage collector issue?) bug that I mentioned. I don't think I ever saw a report about it affecting the c172p, but it certainly did the shuttle in the same random way.

**Comment by camileck** [comment]
Thank you for your answers. I use 2019.1.1 on Ubuntu 16.04. So the version seems to be the root cause here!
