### ISSUE TITLE
Invert mouse wheel set to true, by default...

### ISSUE THREAD

**Issue by sniksnoodle** [c172p-team/c172p#1330]
I fly the C172p a lot, and have noticed  recently that the invert-mouse-wheel is set to true by default. As I use a mouse, this is not ideal for me, so if you find the same you can change line 563 of c172p-set.xml from its current setting of <invert-mouse-wheel type="bool">true</invert-mouse-wheel> to:
<invert-mouse-wheel type="bool">false</invert-mouse-wheel> for a permanent fix.

**Comment by onox** [comment]
This was done on purpose. See 1d92ca5572670d9cefe7d9a39a552959fff2cfc8. The behavior when using the mouse scroll wheel to turn knobs is subjective; some users prefer scrolling up to be turning a knob clockwise, others prefer scrolling up with incrementing the value of the knob (which may be counterclockwise). @wlbragg @gilbertohasnofb is there a mouse wheel setting in that Qt control panel app that @zakalawe is working on ?

**Comment by Juanvvc** [comment]
This inverted mouse, to me, is specially counter-intuitive on the trim wheel.

I expect the mouse wheel to work exactly as the trim wheel, but their rotations are inverted: to trim down the nose, you rotate the trim wheel down->up (same direction than rotation on the pitch axis), or the mouse wheel up->down (reduce trim value)

This is counter-intuitive to me, but I guess it might be only me.

**Comment by gilbertohasnofb** [comment]
> is there a mouse wheel setting in that Qt control panel app that 

I am not sure but I don't think there is one.

> This inverted mouse, to me, is specially counter-intuitive on the trim wheel. [...] This is counter-intuitive to me, but I guess it might be only me.

Definitely not just you, I too think this needs to be inverted. It doesn't make sense visually but it also conflict with the mouse controls. Moving the mouse downwards raises the nose, so scrolling down should also move the nose up.

**Comment by dany93** [comment]
I was on the verge of sending the same remark as @Juanvvc.

Personally and for subjective reasons (among them that I am right-handed) I prefer the current behavior for the knobs (pulling the scroll wheel = potentiometer or knob rotating right-wise and increasing values).

However, it is objectively counter-intuitive for the elevator trim wheel, the throttle, mixture and flap controls.

**Comment by gilbertohasnofb** [comment]
@dany93 I agree with you in relation to other knobs, the current behaviour makes sense. Knobs rotate in a different plane than the wheel, so the physical translation isn't as obvious. For me scrolling up means increasing, just like you would expect on a volume slider, for instance, and so the current behaviour seems good. But we should definitely reconsider the trim, I had never realised it up until now.

I'm happy to create a PR for this later today if nobody beats me to it.

**Comment by dany93** [comment]
@gilbertohasnofb wrote
> For me scrolling up means increasing, just like you would expect on a volume slider, for instance, and so the current behaviour seems good

Confusion? currently, scrolling up (= pushing the scroll-wheel) makes decreasing (see the radio or AP values).

**Comment by gilbertohasnofb** [comment]
@dany93 Sorry, I was wrong, I just checked this and you are right (I think I normally click and drag which is why I got confused). And in my opinion they are all inverted. The throttle and mixture lever as well as the flap are going against you would expect (pushing the scroll wheel is currently pulling the levers and lowering the flap). That goes in the same category as the trim, I think all these four must be addressed. 

As for all other knobs, are other aircraft handling this the same way? It's very unintuitive to me to scroll up to lower a value, that is not how any other GUI works (e.g. volume slider again). I personally would invert absolutely everything.

**Comment by dany93** [comment]
To invert everything, I think it can be done straightforwardly in 
c172p-set.xml, lines lines 562- 565 (on master)
or
c172p-main.xml, lines 565 - 568 (on issue-1327)
```
        <!-- Fix scrolling direction of knobs -->
        <mouse>
            <invert-mouse-wheel type="bool">true</invert-mouse-wheel>
        </mouse>
```

**Comment by gilbertohasnofb** [comment]
@wlbragg @legoboyvdlp @onox @Juanvvc does anyone have a good argument for not inverting everything, only the trim wheel, levers, and flaps?

**Comment by wlbragg** [comment]
I'm ok with changing them.

**Comment by onox** [comment]
> I expect the mouse wheel to work exactly as the trim wheel, but their rotations are inverted: to trim down the nose, you rotate the trim wheel down->up (same direction than rotation on the pitch axis), or the mouse wheel up->down (reduce trim value)

At the time the behavior was that the mouse wheel should move in the same direction as the object in the cockpit. Same with the levers: pushing the wheel (down to up) should push the lever.

If I understand correctly, that is not what is happening right now? (I don't have FG installed here)

**Comment by gilbertohasnofb** [comment]
> Same with the levers: pushing the wheel (down to up) should push the lever. If I understand correctly, that is not what is happening right now?

I think that's incorrect. The levers and flaps were reversed prior to my PR (which hasn't been merged yet), you had to scroll down to increase the throttle, enrich the mixture, or raise the flaps (e.g. you had to scroll down to push in or raise an object, which was very counter-intuitive). Same for the trim wheel, which moved opposite from the mouse scroll direction. This has now been fixed for all things that move vertically.

When it comes to things that move on a different axis than the mouse wheel (e.g. knobs), there is an argument to be made for either direction since the physical movement cannot be translated directly. What tipped the balance in favour of inverting those as well is the convention of scrolling up to increase values on GUI (the example I gave is scrolling upwards above the volume icon in the taskbar of a system to increase the volume). I believe that's how other sims work too if memory serves me right (I don't have any other sim installed). @wlbragg I noticed on my Youtube feed that you are playing the new MSFS, could you check the scroll direction they used on knobs, please?

**Comment by onox** [comment]
> e.g. you had to scroll down to push in

Isn't that the opposite of:

> > pushing the wheel (down to up) should push the lever.

?

**Comment by gilbertohasnofb** [comment]
It's easier to show it, this is the behaviour of levers, flaps, and trim wheel in the branch I created for this issue:

https://www.dropbox.com/s/oge89h844sopyys/VID_20200828_121715130.mp4?dl=0

I think the mouse wheel's movement correspond exactly to how the physical objects move.

**Comment by onox** [comment]
Yeah, that's how it should work :smile: But if I remember correctly that is how it used to work as well in the past (several years ago).

**Comment by gilbertohasnofb** [comment]
Great, we are all on the same page then! I don't know if something happened to change it or not, but it's working fine now, just waiting for the PR to be merged after we decide what to do about an unrelated minor issue being discussed there
