### ISSUE TITLE
Possible bug: yaws to the right during taxiing, but it should yaw left

### ISSUE THREAD

**Issue by sfrsfrsfr** [c172p-team/c172p#1341]
Fwd'd from the [forum](https://forum.flightgear.org/viewtopic.php?f=49&t=38437):

wikw.flightgear.org/JSBSim_Thrusters#Sense_bug_affecting_gyroscopic_movement
refers. Paragraph 3.4.1 says:
`version="1.1"`
should be inserted into the <propeller clause.

This has not been applied to files, for example:
`prop_75in_2f_NACA_15-30deg.xml`
`prop_75in2f.xml`
`prop_76in_2f_NACA_15-20deg.xml`
`prop_76in_2f_NACA_20deg.xml`

These files have in their header:
`<propeller name="XXX pitch XX-inch etc ">`
which should be of the form:
`<propeller name="XXX pitch XX-inch etc" version="1.1">`

**Comment by wlbragg** [comment]
Hum, my version yaws left at full throttle. I added the version number and it didn't appear to change anything.

**Comment by dany93** [comment]
+1 with @wlbragg.

Agreed with your remark about [JSBSim Thrusters: Sense bug affecting gyroscopic moment](http://wiki.flightgear.org/JSBSim_Thrusters#Sense_bug_affecting_gyroscopic_moment).
I had seen this in the past but, for reasons that I don't remember, I had not taken it into account. I have to consider it again.

However, your title ('_yaws to the right during taxiing, but it should yaw left_') is wrong or confusing. The aircraft pulls left (not at  taxiing but...) at full throttle on the runway and takeoff for other reasons, much stronger than the gyroscopic moment. These are mainly propwash effect, weaker P-Factor.
Moreover, during acceleration on the runway before takeoff, (even less taxiing) there is no gyroscopic effect. For a straight trajectory, of course.
Moreover again, when you pull the yoke for takeoff (pitch-up), unless I'm confused, the gyroscopic effect should yaw to the right. 
[Effect of the Propeller on the Aircraft](https://www.mh-aerotools.de/airfoils/prop_precession_english.htm) : See _Estimation of Yawing Moments due to Pitch Rate._

> In case of the common propeller sense of rotation (model aircraft: clockwise when seen from the receiver) the a "pitch up" motion w ("pull") produces a yawing moment q in the direction "rudder to the right". This moment causes the aircraft to deviate towards the right. If the pitching motion w is in the "pitch down" direction ("push") the aircraft feels a tendency to turn to the left. 

Obviously, all these effects have to be checked with no crosswind.

As this effect is much weaker than the other ones, hard to check, I need some time to look at it. 

For this same reason, it would be nice if you could check by yourself, confirm or correct your writing.
Due to the weakness of this effect, cancelling the other ones (spiraling propwash, P-Factor, crosswind) will probably be necessary.

**Comment by wlbragg** [comment]
Thank you for looking at this @dany93 
I noted it was only with "substantial" throttle that it pulled left. Then if backed down I was getting some right pull. But I had live weather and not set up for testing.

**Comment by dany93** [comment]
@sfrsfrsfr, do you follow this thread that you opened?

I've tested, you are right, we have to add `version="1.1"` at the end of each propeller name to get the correct direction for the gyroscopic effect. [JSBSim Thrusters: Sense bug affecting gyroscopic moment](http://wiki.flightgear.org/JSBSim_Thrusters#Sense_bug_affecting_gyroscopic_moment)
Thank you for your remark.

The effect is weak, hard to observe. I had to cancel every other propeller effect and increase the propeller moment of inertia (`Ixx`) from 1.67 to 20. And after that, I had to tweak the engine starter because it could not reach the RPMs.
With the 'normal' `Ixx` (1.67), the gyroscopic effect is almost impossible to notice, much weaker than the other ones.
I'm wondering if the JSBSim calculation would not underestimate its amplitude (calculated from the `Ixx`). I had been able to observe this effect IRL on an ultralight aircraft.

I will upload a merge request.

**Comment by sfrsfrsfr** [comment]
@dany93, not really tbh. i just wanted to let the devs know about this possible issue that was reported in the forum.
especially as the original reporter chose not to open an issue abou it. i'm glad you were able to verify & confirm the issue.

**Comment by dany93** [comment]
Thank you for having forwarded abampton's message.

**Comment by hbeni** [comment]
@HHS81  i think the c182 is also affected...

**Comment by dany93** [comment]
I'm afraid there are many aircraft affected, would it be when Aeromatic did not have `version="1.01"` added in the prop name.

**Comment by wlbragg** [comment]
@dany93 I went ahead and created a PR for this and added version=1.1 to each of the 4 props.

**Comment by dany93** [comment]
Thank you @wlbragg for having done the PR..
I've just merged it.
