### ISSUE TITLE
Parking brake setting for joystick doesnt work.

### ISSUE THREAD

**Issue by Megaf** [c172p-team/c172p#1358]
Setting a joystick button for parking brake, will not switch the parking brake.

**Comment by wlbragg** [comment]
@Megaf 

Sorry for the delay in responding to this.

The property used to set the parking brake is
/sim/model/c172p/brake-parking

Can you describe the details of what your tying to do and how it is not working?

**Comment by Megaf** [comment]
@wkitty42 In File > Joystick Configuration.
You can assign joystick buttons to functions. I assigned a button to toggle the parking brake, but after trying it doesn't work.
Maybe because the Cessna is not using the default/standard property for that.

**Comment by wlbragg** [comment]
Do you know what the standard property for that is?

**Comment by Megaf** [comment]
@wlbragg This is from the Joystick configuration. I didn't get to the script yet.
```xml
  <button n="9">
    <desc type="string">Parking brakes</desc>
    <repeatable type="string">false</repeatable>
    <binding>
      <command type="string">nasal</command>
      <script type="string">controls.parkingBrakeToggle(0);</script>
    </binding>
    <mod-up>
      <binding>
        <command type="string">nasal</command>
        <script type="string">controls.parkingBrakeToggle(1);</script>
      </binding>
    </mod-up>
  </button>
```

**Comment by Megaf** [comment]
@wlbragg 
```
var applyParkingBrake = func(v) {
    if (!v) { return; }
    var p = "/controls/gear/brake-parking";
    setprop(p, var i = !getprop(p));
    return i;
}
var parkingBrakeToggle = func(v) {
    if (v){
        if (getprop("/controls/gear/brake-parking"))
          setprop("/controls/gear/brake-parking", 0);
        else
          setprop("/controls/gear/brake-parking", 1);
    }
}
```

**Comment by wlbragg** [comment]
I'm not understanding a couple things here.

1. What is the default/standard you are referring to?
2. Where is it stated there is a "standard"?
3. What exactly is this aircraft doing that is not default/standard?
4. You can map your joystick to anything you want as far as I am aware.
5. Logically thinking, because there are so many different type of aircraft with different types of braking systems VS different types of controllers. I can't wrap my head around the concept of "a default". Maybe at the most basic level, but certainly not once you get to less than standard systems in any particular aircraft. Thus why logically speaking the mapping system should be robust enough to map anything to anything. You follow what I am getting at.
6. If this isn't using some kind of "default" that other aircraft use and should be, then I need all the specifics about that.

I need specifics because I don't have enough experience with it to know if I have a problem with it. Plus, no one else has reported any issue with it, so that is suspect to me. I also have limited experience with that whole interface. Just enough to hook up my control system T160000M/TWCS/Peddles in a limited way. At the time I was not thrilled with the flow of the entire mapping system and GUI. It was not clear what, why and how it worked.

Keep in mind, many of the basic systems, this one in particular, have been what they are for millennium (ok maybe not a millennium). For me to be able to help, I will need you to research this and feed me the needed information (educate me), or wait until I get back into the flying side and try to enhance my joystick mappings.

I really need to go through the whole process of setting up my control systems again and see what all it entails. I remember it wasn't very intuitive and I didn't totally understand how it all worked.

**Comment by dany93** [comment]
In flightgear/fgdata/keyboard.xml, lines 478 - 761, I see:
```
 <key n="66">
  <name>B</name>
  <desc>Toggle parking brake on or off</desc>
  <binding>
   <command>nasal</command>
   <script>controls.applyParkingBrake(1)</script>
  </binding>
  <mod-up>
   <binding>
    <command>nasal</command>
    <script>controls.applyParkingBrake(0)</script>
   </binding>
  </mod-up>
 </key>
```
These are the lines for toggling with the keyboard, they work with the default c172p. Which makes me think that they are standard, and the c172p too regarding them
Could this instructions lines work with a JS button? They do a toggling with the same signal.

**Comment by wlbragg** [comment]
I think the joystick mapping will be somewhat different, but I don't know that.

I just quickly attached my JS controls and reset them to see what happens by default (in Windows). Right off the bat I don't see a Parking Brake mapping of any kind, only a left and right brake. But the FG joystick interface is not recognizing either left or right brake correctly. The left not at all and the right was reversed. But using the "reverse" switch broke that completely.
I verified in the Windows Control Panel that my JS was being recognized and calibrated correctly and it was. All the pertinent inputs were recognized and spot on. So any issue is an FG issue for sure.
The in sim gui interface wasn't as bad as I recalled and actually looked simple and robust. If it worked that is. So needless to say, there are some issues in "easily" setting up the hardware. But again, there are so many types of controllers VS types of aircraft systems. I wouldn't expect it to be "simple".

We/I need to dig into what signals are mapped between controllers and software, I currently haven't a clue.

**Comment by dany93** [comment]
I tried my [suggestion above ](https://github.com/c172p-team/c172p/issues/1358#issuecomment-869027046)
(from keyboard.xml)
```
<button n="4">
  <name>P-Brake</name>
  <desc>Toggle parking brake on or off</desc>
  <binding>
   <command>nasal</command>
   <script>controls.applyParkingBrake(1)</script>
  </binding>
  <mod-up>
   <binding>
    <command>nasal</command>
    <script>controls.applyParkingBrake(0)</script>
   </binding>
  </mod-up>
 </button>
```
It works with a button on my JS (T.16000M)

**Comment by wlbragg** [comment]
I just went through the JS setup in sim and tried to map the parking brake in the GUI to a JS button and it didn't work. It appeared the "Parking Brake" button mapping in the JS mapping GUI is not calling that nasal script or anything else that sets the parking brake. I think that is what @Megaf is referring to.
I was able to map both left and right brake simultaneously to one JS button. But not the differential braking.

Seems were using the same T.16000 JS.

So how did you bind it? Did you manually edit the JS code to map to that nasal call?

**Comment by Megaf** [comment]
@dany93 I tried with the same joystick, it does not work with the c172p. It does work with the PA-28 which uses the `/control/` subtree.

@wlbragg by standard I mean using the properties define out of the box in FlightGear, like the one I mentioned, which the PA-28 already follows, for example.

I no longer understand anything... I'm using FlightGear 2020.3.9 with the T.16000M and Extreme 3D Pro. Parking brake with the joystick never worked in the Cessna when assigning the button in the joystick configuration window.

The joystick configuration window uses the property I mentioned.

**edit:**
@wlbragg I figured the real issue!
The Cessna is using is indeed correct! The issue is that for some reason it's not toggled with the joystick, I can see it cycling back to the previous setting whenever I try to toggle it with the joystick.

**Comment by Megaf** [comment]
@wlbragg This is what happens when I try to toggle the parking brake using my joystick.
https://user-images.githubusercontent.com/6201512/123521498-e1731000-d6ae-11eb-8d4e-415dc8cf75af.mp4

**Comment by dany93** [comment]
> So how did you bind it? Did you manually edit the JS code to map to that nasal call?

I manually edited my binding JS file (copied the lines inside a button number). I never use the in-sim JS configuration.

**Comment by wlbragg** [comment]
Well that make sense. All this has helped me understand users having issue with the auto setup interface. It has issues for sure. But I was always of the opinion that you can manually do what you did and customize it adequately. But I do understand people wanting the default aircraft using default settings. I'm on the fence about some of this stuff because of program evolution.

**Comment by wlbragg** [comment]
>I no longer understand anything...

I'm right there with you.

This gets complicated.

The property you are referring to controls/gear/brake-parking is influenced by the following logic statement.
So if it is returning to a value it is because of this code.

Is this property the default property mapped in other aircraft to joysticks?

~~~
    <logic>
        <name>Parking Brake And Chock</name>
        <input>
            <or>
                <!-- The actual parking brake controlled by the pilot -->
                <property>/sim/model/c172p/brake-parking</property>

                <property>/sim/model/c172p/securing/chock-visible</property>

                <!-- When changing the bushkit, hold position so that new
                     initial length of tiedowns can be safely computed.
                -->
                <property>/fdm/jsbsim/damage/repairing</property>
            </or>
        </input>
        <output>
            <property>/controls/gear/brake-parking</property>
        </output>
    </logic>
~~~

**Comment by Megaf** [comment]
@wlbragg My assumption with the property been wrong was, wrong. The Cessna is setting/using the right property after all.

The issue is, when using the joystick, configured via the launcher, the property is toggled, but it immediately returns to what it was before.

See https://github.com/c172p-team/c172p/issues/1358#issuecomment-869038025

**Comment by wlbragg** [comment]
I know, what I am telling you is that the above logic code is what is responsible for setting it back to 1 constantly.
If any of the following properties are set to a value other than 0, then /controls/gear/brake-parking will change to 1. Otherwise /controls/gear/brake-parking will always be 0.

/sim/model/c172p/brake-parking
/sim/model/c172p/securing/chock-visible
/fdm/jsbsim/damage/repairing

So you cannot use /controls/gear/brake-parking for the joystick successfully.

@dany93 mapped his JS by way of nasal to 
~~~
var applyParkingBrake = func(v) {
    if (!v) { return; }
    var p = "/controls/gear/brake-parking";
    setprop(p, var i = !getprop(p));
    return i;
}
~~~
Which technically shouldn't work any better because the local logic statement should override it?

There is also this nasal toggle available...
~~~
var parkingBrakeToggle = func(v) {
    if (v){
        if (getprop("/controls/gear/brake-parking"))
          setprop("/controls/gear/brake-parking", 0);
        else
          setprop("/controls/gear/brake-parking", 1);
    }
}
~~~

**Comment by wlbragg** [comment]
So what should be mapped to the JS for it to work correctly is
/sim/model/c172p/brake-parking

But that is definitely not the default property that should be used throughout FG for the Paring Brake.

**Comment by wlbragg** [comment]
This is a direct effect of using the logic statement to trigger the parking brake when the chocks are deploy. That system needs to be reexamined.

This is similar to the issue that Stuart has with the throttle mapping to the joysticks for multiple engines. People want to use the "default" mapping of /controls/engines/engine[X]/throttle. But we can't because we rely on /controls/engines/throttle-all for multiple engines. In this case that is also a default, except there is some issue with certain quadrants that have multiple throttle controls where you need to use /controls/engines/engine[X]/throttle.
I noted this throttle issue here because while I am re-educating myself with the controller interface and mapping for the brake, I may revisit that as well as it was left unresolved.

**Comment by Megaf** [comment]
Can't you simply set more than one property at the same time?

**Comment by dany93** [comment]
Weird... [JS binding = keyboard code](https://github.com/c172p-team/c172p/issues/1358#issuecomment-869032092)
@dany93 wrote

> It works with a button on my JS (T.16000M).

@Megaf wrote

> I tried with the same joystick, it does not work with the c172p
@wlbragg wrote

> Which technically shouldn't work any better because the local logic statement should override it?

I don't understand... This is the same code as shift-B on the keyboard.
**Does Shift-B on the keyboard work for you with the c172p?**

@wlbragg 
Please, did you test this code by manually copying the lines inside some button into your (or a) JS binding code?

**Comment by wlbragg** [comment]
@dany93 
>Does Shift-B on the keyboard work for you with the c172p?

Yes it does. But shift-b sets /sim/model/c172p/brake-parking = 1 due to a local override of fgdata shift+b.
So that meets the logic statements condition to set /controls/gear/brake-parking to 1.

You said you inserted controls.applyParkingBrake(1) which bypasses our local override of shift+b, thus the conditions of the logic statement aren't met and the logic statement should set it back to 0 immediately.

Now if you copied set /sim/model/c172p/brake-parking = 1 directly to the JS binding code that would work correctly because the logic code uses /sim/model/c172p/brake-parking = 1 as a flag to set /controls/gear/brake-parking =1.

>did you test this code by manually copying the lines inside some button into your (or a) JS binding code?

No, I didn't yet. I was just looking at the logic of the code and that logic statement is the overarching control over that property. Thus that property should always be under the logic statements control no mater what other code tries to influence it. The logic statement is at the JSBSim level and the JS controller logic is at the nasal level. 
So, either I am miss identifying properties or nasal has the final say in the process or I am missing some other aspect of this. You did say you inserted the nasal call and not the set property call into the JS button binding, right?
I'll try it sometime today and see where I end up. I don't doubt is is working as you say, I just want to understand why that is, because it shouldn't.

@Megaf 
>Can't you simply set more than one property at the same time?

Sure, but then your back to customized settings that might not fit defaults people expect and I am not sure how that help with this particular issue? Set what, where?

**Comment by dany93** [comment]
> You did say you inserted the nasal call and not the set property call into the JS button binding, right?

I just copied the code given in [this message](https://github.com/c172p-team/c172p/issues/1358#issuecomment-869032092).

**Comment by Megaf** [comment]
> Does Shift-B on the keyboard work for you with the c172p?
Yes.

**Comment by wlbragg** [comment]
OK, here is the deal and we have a conundrum!

Three different ways to set the parking brake, 2 should not work, one should work. But instead 2 work and 1 does not.

I directly inserted the following 3 methods n the JS binding.


This should absolutely work based on the logic of all executing code.
~~~
  <!button>
    <desc type="string">Parking Brake</desc>
    <binding>
      <command type="string">property-toggle</command>
      <property type="string">/sim/model/c172p/brake-parking</property>
    </binding>
  </button>
~~
It does work as it should. It sets the JSBSim logic statement flag /sim/model/c172p/brake-parking that sets /controls/gear/brake-parking = 1

This option should absolutely not work based on the logic of all executing code. but it does.
~~~
  <button>
    <desc type="string">Parking Brake</desc>
	<binding>
		<command>nasal</command>
		<script>controls.applyParkingBrake(1)</script>
	</binding>
  </button>
~~~
 This shouldn't work as it does not touch the condition flags in the JSBSim logic statement. So the logic statement should reset it back to 0 after the nasal statement executes the change. But for some, as of yet, unknown reason, it works and the logic statement isn't setting it back to 0.
This is what the nasal call executes for this call...
~~~
var applyParkingBrake = func(v) {
    if (!v) { return; }
    var p = "/controls/gear/brake-parking";
    setprop(p, var i = !getprop(p));
    return i;
}
~~~

This option should absolutely not work based on the logic of all executing code. and it indeed does not work
~~~
 <button>
    <desc type="string">Parking Brake</desc>
	<binding>
		<command>nasal</command>
		<script>controls.parkingBrakeToggle(1)</script>
	</binding>
  </button>
~~~
 This is what the nasal call executes for this call...
~~~
var parkingBrakeToggle = func(v) {
    if (v){
        if (getprop("/controls/gear/brake-parking"))
          setprop("/controls/gear/brake-parking", 0);
        else
          setprop("/controls/gear/brake-parking", 1);
    }
}
~~~

I didn't watch the JSBSim logic statement flag of /sim/model/c172p/brake-parking while executing each of these methods. I'll do that now.

**Comment by wlbragg** [comment]
OK, I found it, we also override the fgdata nasal function controls.applyParkingBrake in Nasal/c12p.nas
~~~
controls.applyParkingBrake = func (v) {
    if (!v) {
        return;
    }

    var p = "/sim/model/c172p/brake-parking";
    setprop(p, var i = !getprop(p));
    return i;
};
~~~
We should also override controls.parkingBrakeToggle

**Comment by legoboyvdlp** [comment]
The correct way to do it is probably to use /control/gear/brake-parking to represent the handle control -- and then do the logic elsewhere in JSBSim (of course, including chocks, etc). That is; the property /control/gear/brake-parking shouldn't be used directly to apply the brakes, but it should be used only to represent the physical control. Richard talked about this at length in Discord.  The reasoning is to avoid having to override controls, and for ease of use of joysticks. 

I don't have a joystick so I can't implement this.

But regardless, the A320 does it like this:

```
<fcs_function name="fcs/right-brake-input">
			<function>
				<product>
					<property>fcs/brake-avail</property>
					<max>
						<property>/services/chocks/enable</property>
						<property>fcs/brake-right</property>
						<product>
							<property>/controls/autobrake/brake-right</property>
							<property>/controls/autobrake/active</property>
						</product>
						<property>/controls/gear/brake-parking</property>
					</max>
				</product>
			</function>
			<clipto>
				<min>0</min>
				<max>1</max>
			</clipto>
		</fcs_function>
		
		<actuator name="fcs/right-brake-actuator">
			<input>fcs/right-brake-input</input>
			<rate_limit>10</rate_limit>
		</actuator>
		
		<switch name="rubbish/right-brake-cmd-norm">
			<default value="fcs/right-brake-actuator"/>
			<test value="1">
				/systems/acconfig/autoconfig-running eq 1
			</test>
			<output>fcs/right-brake-cmd-norm</output>
		</switch>
```

**Comment by wlbragg** [comment]
@legoboyvdlp 
After studying what you wrote I think I understand what your saying.

Use the FDM's FSC functions instead the control input property, right?

/controls/gear/brake-parking is probably setting some fcs object, right?
We need to set that same fcs object instead of setting /controls/gear/brake-parking, right?

That make total sense to me.

Do you know what exactly /controls/gear/brake-parking is setting in the fdm?

I don't know why this wasn't done in the first place.

Thinking in these terms might help me with Richards issue with the engine controls.

**Comment by wlbragg** [comment]
I tried the following and it seems to work. It solves the problem of having to override any default properties or nasal control commands.
~~~
<channel name="Parking Brake">		
    <summer name="fcs/parking-brake-sum">
        <input>/sim/model/c172p/brake-parking</input>
        <input>/sim/model/c172p/securing/chock-visible</input>
        <input>/fdm/jsbsim/damage/repairing</input>
        <input>/controls/gear/brake-parking</input>
    </summer>
		
    <fcs_function name="fcs/left-brake-cmd-norm">
        <function>
            <property>fcs/parking-brake-sum</property>
        </function>
    </fcs_function>
    <fcs_function name="fcs/right-brake-cmd-norm">
        <function>
            <property>fcs/parking-brake-sum</property>
        </function>
    </fcs_function>
</channel>
~~~
and to control the lever animation
~~~
	<filter>
        <name>Controls Parking Brake Lever</name>
        <type>noise-spike</type>
        <max-rate-of-change>2.5</max-rate-of-change>
        <enable>
            <condition>
                <not>
                    <property>/sim/freeze/replay-state</property>
                </not>
            </condition>
        </enable>
        <input>
	    <condition>
		<or>
		    <property>/sim/model/c172p/brake-parking</property>
		    <property>/controls/gear/brake-parking</property>
		</or> 	
            </condition>
	    <value>1.0</value>
        </input>
	<input>
	    <value>0.0</value>
        </input>
        <output>
            <property>/sim/model/c172p/cockpit/parking-lever</property>
        </output>
    </filter>
~~~

**Comment by wkitty42** [comment]
> The correct way to do it is probably to use /control/gear/brake-parking to represent the handle control -- and then do the logic elsewhere in JSBSim (of course, including chocks, etc). That is; the property /control/gear/brake-parking shouldn't be used directly to apply the brakes, but it should be used only to represent the physical control.

:arrow_up: this! totally this...

>  Richard talked about this at length in Discord. The reasoning is to avoid having to override controls, and for ease of use of joysticks.

yes he did... and he explained it quite well, too... someone should probably go back and grab all of that discussion and save it somewhere where it can be easily found, too...

**Comment by legoboyvdlp** [comment]
Yeah; that works ; but you also need to consider the effect of normal braking. That's on me; I didn't copy and paste the whole snippet.


I can add the necessary code shortly to your branch. Thanks for doing this!

**Comment by dany93** [comment]
It works. Normal braking included.
Thanks @wlbragg and @legoboyvdlp.
