### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#1433]
KAP140 is missing a couple definition blocks of code causing an error in the log.
The material assignment of several properties to buttons and annunciators were deleted subsequently causing a log error. This reintroduces those material assignments.

Amphibious gear are to be up or down depending on startup location or the current location when executing a gui variant change to amphibious.

**Comment by wlbragg** [comment]
The amphibious gear are designed to exhibit the following characteristics...

On initial sim loading or a GUI variant change to the amphibian variant the gear selector knob and gears should be set to match the current location. If on land gear should be down, if on water gear should be up.

The gear control breakers should adhere to the GUI selection of "Save state of aircraft between sessions".
If that is selected. say for a cold and dark startup with breakers out (not connected), then the breakers will stay as they were when exiting the sim.

If the "Save state of aircraft between sessions" checkbox is not selected, then the breakers will always be set to engaged (connected).

When switching variants in-sim (GUI), then the breakers will be set to engaged (connected).

Autostart should set the breakers to engaged (connected).

**Comment by dany93** [comment]
@wlbragg wrote

>KAP140 is missing a couple definition blocks of code causing an error in the log.
The material assignment of several properties to buttons and annunciators were deleted subsequently causing a log error.

Correct now. The two lines, `[ALRT]:io Could not find at least one of the following objects for animation: 'annunciators' (....), 'buttons' (....)/Instruments/kap140/kap140.xml`
no longer appear.

>The amphibious gear are designed to exhibit the following characteristics...

>On initial sim loading or a GUI variant change to the amphibian variant the gear selector knob and gears should be set to match the current location. If on land gear should be down, if on water gear should be up.

Correct on initial sim loading or after a GUI variant change.

>The gear control breakers should adhere to the GUI selection of "Save state of aircraft between sessions".
If that is selected. say for a cold and dark startup with breakers out (not connected), then the breakers will stay as they were when exiting the sim.

Correct

>If the "Save state of aircraft between sessions" checkbox is not selected, then the breakers will always be set to engaged (connected).

Correct.

>When switching variants in-sim (GUI), then the breakers will be set to engaged (connected).

Correct

>Autostart should set the breakers to engaged (connected).

Correct

>Using "Go Now" button or "Aircraft go to Location" relocation, the gear control knob should exhibit the same characteristics as above.

Correct for the knob position vs ground or water. But the correct amphib and wheel position on the ground might depend on the initial loading state. Once, from ground to ground relocation the amphib floats appeared in a first step drowned in the ground, with "Default" option checked in the GUI. However, back to correct after selecting the Amphib option in the GUI. In another test the Amphib with wheels appeared correct on the ground. 
(not an issue IMO,too many unrealistic choices).
> breakers should remain as they were before the relocation.

(with "Save state of aircraft between sessions" unchecked)
Correct for "Aircraft go to Location" (Location > Position Aircraft in Air)
Not for "Go Now" to Seaport (not important IMO, this is a unrealistic change, only comfort for in a simulator)


There are too many possibilities, I think I haven't checked all the combinations.
The most important features work correctly, only one or a few ones might fail in particular circumstances. But of minor importance.
If you think I've responded enough to your tests, I can merge. Otherwise, tell me which extra tests you'd like me to do. Or to elaborate my responses.

**Comment by wlbragg** [comment]
>There are too many possibilities, I think I haven't checked all the combinations.
The most important features work correctly, only one or a few ones might fail in particular circumstances. But of minor importance.

>If you think I've responded enough to your tests, I can merge.

Thanks for testing. Ya, think we're good. I agree, the main points are covered. Go ahead and merge.

**Comment by dany93** [comment]
@wlbragg 
I got this several times at launching (10 or more, with some changes in the method).
The aircraft appears like this
![c172p-bug-launch2](https://github.com/c172p-team/c172p/assets/11994061/f3d75bb3-45ef-4a66-a7f1-0fe52888fcc6)
![c172-bug-amphib-launch3](https://github.com/c172p-team/c172p/assets/11994061/bd7c0418-d340-4eff-9ed4-a1c852d38c21)

At least one way to get it:
("Save state of aircraft between sessions" is unchecked)
- Launch with --aircraft=c172p
- Select amphibious,
- "Go Now"
- Quit
- Again, Launch with --aircraft=c172p

**"Go Now" seems to be the way to repeatedly get the bug.**

Can easily be recovered (fixed) "above" (!!) ground by selecting "Default", or above water by selecting "Float".

**Comment by wlbragg** [comment]
@dany93 thanks, I'm looking into it. Hopefully I'll post a new issue and PR to correct it.
