### ISSUE TITLE
model pitot icing

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p#50]
PRC12 - model pitot icing

**Comment by legoboyvdlp** [comment]
I have a simplistic icing model on the IDG-A32X... it's basic, but it works. The real problem is modelling the effect it has on the instrumentation.

And the pitot cap should also affect the icing rate as well... :)

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/47166508-44079180-d2f4-11e8-8036-92e4e248e402.png)

**Comment by callahanp** [comment]
Today I went to an open house at a local airfield 6B6. I got a chance to
talk to a pilot's spouse who researched acquisition and maintenance of
theirC172 heavily.  He knew quite a lot about the various models.  They
bought a 1999 version.

While walking by the covered pitot tube, I mentioned this thread.  He said
he learned from experience, that a pitot tube left uncovered after a flight
attracts mud dauber wasps who quickly gum up the works. Not sure what they
did to get them out. Turns out these insectes arenotorious for this.
https://en.wikipedia.org/wiki/Mud_dauber &
https://en.wikipedia.org/wiki/Mud_dauber#Airplane_incidents

-Pat

**Comment by dany93** [comment]
As the measure (pressure) is done in principle with a zero flow, I would rather expect a brutal effect. As long as there is a small hole left, the pressure will establish (possibly more slowly on changes, but is it noticeable?). The only thing that can give a very small flow is the leaks in the pipes between the pitot tube and the instrument.

It would be very different for a pipe with a flow (fuel from a tank to the carburetor).

**Comment by callahanp** [comment]
Yeah, too much.

I'm not asking for this, but it's fun to imagine simulating a number of
wasps coming out of the pitot tube and chasing the walker or landing on the
windshield after starting up.  We can leave this to the entomologists among
us to implement.

So what's next? Bird Strikes? ;-)

-Pat

I was stung at age 4 by a number of angry hornets. I was curious to see
them so I kept pedaling my toy tractor into the garage door where they
attached their nest until they came out to play.  I'm still not afraid of
stinging insects, but very respectful.

**Comment by hbeni** [comment]
IIRC this was already implemented recently.
My log confirms this.

```
26.12 [INFO]:nasal      creating PitotIcingHandler for /systems/pitot[0]
26.12 [INFO]:nasal      creating StaticIcingHandler for /systems/static[0]
```

**Comment by wlbragg** [comment]
Thanks, yes.
