### ISSUE TITLE
Create startup states and save mission state

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p#789]
> This seems so obvious, but I haven't found a way to do this in fg 2016.2.1. I want to fly to an airport and stay there "overnight" and continue my trip the next time I start flightgear. The plain should be where I parked it on that airport I landed on.
> I really found no way to do that and I searched online for quite some time to find an answer.
> Thanks,
> Jay

See https://forum.flightgear.org/viewtopic.php?f=17&t=29993#p290183

Think it would be possible to implement something like this as a saved state to allow a convenient way to continue a session?

Other thought's would be adapting the flight recorder to accomplish the same thing?

Just a thought, we may want to discuss it.

**Comment by gilbertohasnofb** [comment]
That sounds super interesting -- I'd love to have this feature -- but how would we override the FG launchers? That is, every launcher for FG I know must have a start location defined. Is there any way to go around this?

**Comment by wkitty42** [comment]
On 07/08/2016 03:23 PM, Gilberto Agostinho wrote:
> That sounds super interesting -- I'd love to have this feature

it sounds nice and may be something to consider once the state file stuff is
finalized...

> but how would we override the FG launchers? That is, every launcher for FG I
> know must have a start location defined. Is there any way to go around this?

i think that's the problem that will stop this from being done in-craft... the
users must specify their starting location... until parking is repaired in the
sim code, there's going to be complaints about it not working...

part of the new state setting stuff is supposed to allow us to set everything as
needed for certain states... for example, if someone chose to start on 10-mile
final, that state file would allow us to have the engine running and everything
else necessary to start there rather than having to start cold or select to
start with engine running and then hope we don't fall out of the sky...

**Comment by gilbertohasnofb** [comment]
Maybe an option to start at the previous location could be available in the launcher rather than in-craft. It would make much more sense IMO.

**Comment by wlbragg** [comment]
I agree the ideal way would be the launcher or simulator shell. However I really don't think this necessarily would be difficult to do. Think about Torsten's browser based map. You can drag and drop the aircraft at any point and relocate it to any other position on the map. So that means there is the capability with code to do this after init. All this would require on our part is to make a menu choice to say, "Save Flight". That would save the position, orientation and trigger the "Save all switch settings" or not, and anything else we wanted to persist. Then on load and init, nasal checks the "Save Flight" switch and if true it moves the aircraft as per Torsten's method to the saved state information. I really don't see this as a difficult problem if we want to do it. Another way might be to adapt the flight recorder and saved tapes. With all that said however, how much more difficult is it to just start the sim in the last location you flew to (unless it's not a valid startup airport).
I could see this as being a cool thing to have for a bush flight to a remote camp site and fly back the next day or something like that.

**Comment by gilbertohasnofb** [comment]
I didn't know about this feature. Well, that sounds really cool :smile:

**Comment by onox** [comment]
> I could see this as being a cool thing to have for a bush flight to a remote camp site (even non-seaport water landings) and fly back the next day or something like that.

Perhaps create a GUI window to store and load positions?

**Comment by wlbragg** [comment]
Yeah, I think that is the best way to handle it. I like the automatic approach, but it is error prone.

**Comment by wlbragg** [comment]
Time to revisit this considering Jame's latest work. I want to create the standard "automatic" states that are supposed to work with the newest launcher. I also want to add a "Save" state GUI option that will save your current location, "parked on the ground".
There is the possibility of saving an "in-flight" state, but this wouldn't be my priority.

**Comment by wkitty42** [comment]
On 02/12/2018 08:33 AM, wlbragg wrote:
> Time to revisit this considering Jame's latest work. I want to create the 
> standard "automatic" states that are supposed to work with the newest launcher. 


we have a couple of these already in place, don't we? someone, james, i think, 
added them to the c172p in FGData for testing the concept... i don't remember if 
those changes ever made it back into this repo...


> I also want to add a "Save" state GUI option that will save your current 
> location, "parked on the ground".


someone will undoubtedly try to use "save your current location" to save their 
place in the air ;)


> There is the possibility of saving an "in-flight" state, but this wouldn't be my 
> priority.


one of the things that these states are supposed to allow for is the starting at 
10nm out on final... or maybe not just 10nm but Xnm as selectable in the 
launcher... either way, the idea is that the sim will run the FDMs for some 
period of time in order to let everything stabilize in the in-air scenario so 
that when it removes the splash screen and let's you have control, everything 
will be up and operational as if you had actually flown there...

**Comment by wlbragg** [comment]
>we have a couple of these already in place, don't we?

Yes but they need revamped to take advantage of the current launcher algorithms James coded.

>someone will undoubtedly try to use "save your current location" to save their place in the air ;)

I plan on coding it in such a way that you can't save it unless your in a predefined configuration, such as on the ground with the brake on and engine off. Or something to that effect.

>one of the things that these states are supposed to allow for is the starting at 10nm out on final

Right, the c182s has implemented a nice state system. I'll be looking at that in detail.

I also implemented 7 states in the Cub that work really well, including an approach state. These were created prior to this latest launcher work. 
The Cub has the following states available (they were mainly for testing) and I am not sure they are all pushed to fgaddon.
approach
glacier
hilltop
ice
mountain
parking
tahoe
They use different aircraft configurations such as pontoons, skis or bush, etc. I really enjoyed using some of them like tahoe which sets you up ready to land on lake Tahoe. We can do the standards like approach, parking, etc. and also maybe one for each gear configuration, kind of like I did for the Cub.

**Comment by wlbragg** [comment]
I'm adding this to the "Fixes" list in the save-state PR. I will start a new issue for the Startup States after this release is finished.
