### ISSUE TITLE
Gear: skis do not work on ice

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#946]
Hi there!
Just reporting that when I tested the skis do not work on frozen water (winter textures)... the aircraft just sticks to the ground and doesn't move. Is it possible to make the FDM treat water as ice when it is frozen? Thanks!

**Comment by gilbertohasnofb** [comment]
Hmm, I think as far as FG is concerned a frozen water is still just water, isn't it? It does not become solid ground, or does it?

**Comment by wlbragg** [comment]
@legoboyvdlp, if not to much trouble, could you please check the J3Cub with skis on the same surface and let me know what it does. Also can you give me the lat/lon of this terrain and the weather/season you were using?

**Comment by legoboyvdlp** [comment]
Sure. 
Wlbragg, I'm not entirely certain where exactly it is... I was just flying around in Alaska ;)
It is somewhere in the PATK region, perhaps close to 13AK?

I'll try the Cub.

**Comment by onox** [comment]
It would be nice if you could land on ice indeed, but likely needs to be fixed in FG itself.

**Comment by wlbragg** [comment]
Hum, interesting. I wonder if we need to consider adding some skis without the wheels like the Cub has, they work great on glaciers and ice.

**Comment by wlbragg** [comment]
I have taken the first steps to correct this. My first inclination was to make real skis like the cub has, without wheels. Because those are contact points and not bogey. They work with the ground-cover friction factor as is.
But I decided as a test case this should be corrected with the skis and wheels combination as this is a duel use case configuration and should work as such.
So, the first stage was to use a switch to change the dynamic, static and rolling friction factors of the gear when...
bushkit = ski
and
alt-m > snow-level-m

Simple enough and should help in some cases.

Still to do, change the dynamic, static and rolling friction factors of the gear when...

ground-cover friction factor < ?

I still have to determine that value.

**Comment by legoboyvdlp** [comment]
Sorry... I never checked this! Regardless, sounds good.
