### ISSUE TITLE
Engine misbehaves beyond 265 degF oil temperature

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p#979]
While testing the Lycoming I deliberately maxed the engine on the ground while leaning the mixture to increase EGT - as the oil temperature reached 265, the engine began to flicker between killed and not killed, doing 350+ RPM jumps -> this indicates a bug, as the engine should probably overheat and then just die as the oil overheats? It should not repeatedly kill the engine then turn it back on.

I realise that the redline exists for a reason, but this seems to be a bug --> I'll look into it, but if anyone else could fix it, it would be great :)

I'd also like this to be confirmed, and not just a bug I introduced when I simulated the engine dying due to low oil pressure.

**Comment by gilbertohasnofb** [comment]
> but this seems to be a bug 

That's actually a feature. Since we don't have damage implemented, the oil temp code shuts down the engine at very low oil, simulating a broken engine. If you take care of implementing the engine damage then this needs to be modified. Should be quite trivial to do so but I am happy to help you if you need a hand finding your way on my previous code. The oil management is controlled by the function `oil_consumption` at `engine.nas`

**Comment by legoboyvdlp** [comment]
Thank you: so the engine damage at high temperature is also simulated, or does the pressure drop as temperature rises? I did not touch the oil level... this was with a full seven quarts of oil :)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp engine dies in relation to low oil level, but low oil level causes temperatures to rise. You possibly will want to uncouple the latter one if you are going to truly simulate damage and oil temp effects.

**Comment by legoboyvdlp** [comment]
OK. I will do my best... :)

My issue occured when going at full throttle until oil temp rose beyond 265 degF, 20deg past the limit... did not check if it was my bug or yours. 

It doesn't look like a cough, but an actual bug.

**Comment by gilbertohasnofb** [comment]
Cool Lego, give me a shout if I can help with anything! Thanks for taking a look at this issue here.

**Comment by legoboyvdlp** [comment]
The oil pressure decreases as temperature increases - this behaviour is incorrect

**Comment by okroth** [comment]
Oil pressure decrease with rising temperature as the oil's viscosity becomes smaller; it just flows better though all those tiny holes and the oil pump build up less pressure.
Also the oil's capacity to lubricate decreases with smaller viscosity; exceeding the red line will not stop the engine running due to low oil pressure but because the metal-metal friction damages the pistons.

**Comment by wlbragg** [comment]
>but because the metal-metal friction damages the pistons.

I've experienced this in a Briggs & Stratton engine before. It is running along (for all appearances running fine) and suddenly it just seized up. It does have a distinct metallic sound though right as it is going through it's last few strokes.
In this instance I ran it dry of oil.

Now, as far as starting back up. No, not by itself, however after short amount of air cooling you potentially could start the engine again if nothing actually broke. I was able to do that in this case. However I ended up replacing the rings as I was pretty sure they were toast.

**Comment by legoboyvdlp** [comment]
Actually, sorry -  I need to check this does not still exist, I probably fixed it already.

**Comment by gilbertohasnofb** [comment]
I am leaving now but I will test this later in the evening if no one beats me to it.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I can't reproduce this. 6000 ft, max throttle, lean to max EGT and temps are all in the green arc below 245. Temps look very stable. Please try to reproduce it again yourself, maybe you need another step/requisite in order to reproduce this.

**Comment by legoboyvdlp** [comment]
I did it on the ground on a fairly warm day?
That might be what you need. Regardless the bug is not an over temp but the engine going "crazy" when it gets too hot, jumping +- 500rpm, and coughing.

**Comment by gilbertohasnofb** [comment]
Could you please try to reproduce it? There shouldn't be any difference between being in the air or on the ground, possibly the difference is in the weather or some other settings.

**Comment by legoboyvdlp** [comment]
In the air it's considerably cooler, so it should be harder to get the high temperatures surely? Anyway, that's fine, I can ;)

**Comment by legoboyvdlp** [comment]
and finally we can close it... :) I don't see this anymore.

sorry for the long delay

**Comment by onox** [comment]
@legoboyvdlp You didn't manage to reproduce it anymore? Could you add label 'invalid' and remove the milestone otherwise it looks like something that was fixed.

**Comment by wkitty42** [comment]
if i may submit: possibly it wasn't invalid but the ultimate bug that was causing it so it was seen in this craft was fixed in the meantime... i'm thinking of function validations and JSBsim updates in the core... just sayin' and i don't think this issue needs to be changed as it stands... unless it reappears, of course :cat2:
